---
name: Java CI

on:
  workflow_dispatch:
    inputs:
      runid:
        description: 'Run id'
        required: true
        default: '1'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dist: [temurin, zulu, adopt]
        java: [8, 11, 17]
      fail-fast: false
      max-parallel: 27
    name: Test JDK ${{ matrix.dist }}, ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.dist }}
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        env:
          cache-name: cache-maven-modules
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}
      - name: Test with Maven
        run: 
          mvn test -B --file pom.xml -"Drat.skip=true" -fn
        continue-on-error: true
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}_testresults-env-${{ github.event.repository.name }}-${{ matrix.os }}_${{ matrix.dist }}_${{ matrix.java }}-saflateoff-${{ github.event.inputs.runid }}
          path: ${{ github.workspace }}/**/*.xml

